sample_id: sample_id
mom_label: mom_id
dad_label: dad_id
hom_vcf: /path/to/homozygous.vcf
mom_phased_vcf: /path/to/mom.phased.vcf
dad_phased_vcf: /path/to/dad.phased.vcf
reference_genome: /path/to/genome.fa
phased_chrom: "1 2 3 4"
unphased_chrom: "X Y MT"
unphased_label: dad_id