sample_id: sample_id
mom_label: mom_id
dad_label: dad_id
hom_vcf: /path/to/homozygous.vcf
mom_phased_vcf: /path/to/mom.phased.vcf
dad_phased_vcf: /path/to/dad.phased.vcf
reference_genome: /path/to/genome.fa
phased_chrom: /path/to/phased.txt
unphased_chrom_X: /path/to/unphased_X.txt
unphased_chrom_Y: /path/to/unphased_Y.txt